
const ALERT = "ALERT"
const REFETCH_CHATS = "REFETCH_CHATS"
const NEW_MESSAGE = "NEW_MESSAGE"
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT"
const NEW_REQUEST = "NEW_REQUEST"
const START_TYPING = "START_TYPING"
const STOP_TYPING = "STOP_TYPING"
const CHAT_JOINED = "CHAT_JOINED"
const CHAT_LEFT = "CHAT_LEFT"
const ONLINE_USERS = "ONLINE_USERS"

export {
    ALERT, REFETCH_CHATS, NEW_MESSAGE, NEW_MESSAGE_ALERT, NEW_REQUEST, START_TYPING, STOP_TYPING, CHAT_JOINED, CHAT_LEFT, ONLINE_USERS
}